### ISSUE TITLE
Spec 1.3.0 Issues

### ISSUE THREAD

**Issue by Kerilk** [oneapi-src/level-zero#72]
Hello,
I had a bit of time to go over the 1.3.0 specification. I noticed a few issues. This was not thorough so there may be more.
- zeDevicePciGetPropertiesExt:
  - `pProperties` is inconsistently named => `pPciProperties`
  - https://github.com/oneapi-src/level-zero/blob/7afa8a6dda56d4baef950c0a9d5ef8d8b0e14c4e/include/ze_api.h#L6988
- zeMemFreeExt
  - `desc` is inconsistently named => `pFreeDesc` or `pMemFreeDesc` or `pMemoryFreeDesc`
  - https://github.com/oneapi-src/level-zero/blob/7afa8a6dda56d4baef950c0a9d5ef8d8b0e14c4e/include/ze_api.h#L7459
- ze_srgb_ext_desc_t
  - Uses `bool` instead of `ze_bool_t`
  - The <stdbool.h> is not included so including the file will fail on C compilers
  - https://github.com/oneapi-src/level-zero/blob/7afa8a6dda56d4baef950c0a9d5ef8d8b0e14c4e/include/ze_api.h#L7026

**Comment by jandres742** [comment]
hi @Kerilk  thanks for checking it out!

>zeDevicePciGetPropertiesExt:
pProperties is inconsistently named => pPciProperties

Yes, we could change it.

>zeMemFreeExt
desc is inconsistently named => pFreeDesc or pMemFreeDesc or pMemoryFreeDesc

Could be. Most of our descriptors variables We have other functions with desc, like zeCommandQueueCreate and zeCommandListCreate. 

> ze_srgb_ext_desc_t
Uses bool instead of ze_bool_t

Correct. We were already made aware of that one and a fix is coming.

**Comment by bmyates** [comment]
These issues were addressed here: https://github.com/oneapi-src/level-zero/commit/7f42f3c6e9599a9bcd995792e2bc42be27ec05ab
