### ISSUE TITLE
ze_device_kernel_properties_t.dp4aSupported contains garbage

### ISSUE THREAD

**Issue by maleadt** [oneapi-src/level-zero#8]
```
ze_device_kernel_properties_t kernel_properties;
kernel_properties.version = ZE_DEVICE_KERNEL_PROPERTIES_VERSION_CURRENT;
kernel_properties.dp4aSupported = 100;
zeDeviceGetKernelProperties(allDevices[d], &kernel_properties);

printf("dp4aSupported: %i\n", kernel_properties.dp4aSupported);
```

This retains the `100` value. Am I supposed to zero-initialize these structs?

Also, is the use of the `version` field correct here?

**Comment by jandres742** [comment]
`version` is correct. You don't need to set the other values, as that's the only input parameter, and the others are outputs (see definition for that struct here https://spec.oneapi.com/versions/0.6.0/oneL0/core/api.html?highlight=zedevicecanaccesspeer#_CPPv429ze_device_memory_properties_t). The rest are set by the driver when retrieving the properties.

Reason that field retains the value is because it's a boolean, so the driver most likely is just setting up to true, which is the same as 100 :)

**Comment by maleadt** [comment]
> Reason that field retains the value is because it's a boolean, so the driver most likely is just setting up to true, which is the same as 100 :)

That doesn't appear to be the case, if I memset the struct to zero (or set the dp4aSupported field to 0) that value is preserved too, so it rather looks like the driver isn't setting anything.

**Comment by jandres742** [comment]
Ok, so in this case, it looks like there's something missing in the implementation. Could you please create the issue in the Intel driver implementation, https://github.com/intel/compute-runtime, given that it looks like a bug in the GPU driver implementation and not in the loader?

**Comment by maleadt** [comment]
Done!
